### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by dangreen** [yortus/DBFFile#4] opened 2015-05-26 11:14 UTC
```
var DBFFile = require('dbffile');

DBFFile.open('[full path to .dbf file]')
.then(function (dbf) {
  console.log('DBF file contains ' + dbf.recordCount + ' rows.');
  console.log('Field names: ' + dbf.fields.map(function (f) { return f.name; }).join(', '));
  return dbf.readRecords(100);
})
.then(function (rows) {
  rows.forEach(function (row) {
    console.log(row);
  });
})
.catch(function (err) {
  console.log('An error occurred: ' + err);
});
```

First callback never called.

**Comment by dangreen** [comment] 2015-05-26 11:19
``` js
var fieldDescriptors = [
  { name: 'fname', type: 'C', size: 255 },
  { name: 'lname', type: 'C', size: 255 }
];

var rows = [
  { fname: 'Joe', lname: 'Bloggs' },
  { fname: 'Mary', lname: 'Smith' }
];

DBFFile.create('my.dbf', fieldDescriptors)
.then(function (dbf) {
    console.log('DBF file created.');
    return dbf.append(rows);
})
.then(function (dbf) {
    console.log(rows.length + ' rows added.');
    return DBFFile.open('my.dbf');
})
.then(function (dbf) {
        // NEVER CALLED
    console.log('DBF file contains ' + dbf.recordCount + ' rows.');
    console.log('Field names: ' + dbf.fields.map(function (f) { return f.name; }).join(', '));
    return dbf.readRecords(100);
})
.catch(function (err) {
    console.log('An error occurred: ' + err);
});
```

**Comment by yortus** [comment] 2015-05-26 12:24
I pasted your code into a file and ran it without problems. The final `then` callack is geting called for me.

What OS/Node version are you using?

**Comment by dangreen** [comment] 2015-05-26 12:25
@yortus  OS X 10.9 node v0.12.2

**Comment by yortus** [comment] 2015-05-26 12:43
OK, I've just repro'd the problem on ubuntu. I don't have an OSX machine. I didn't think anybody would be using DBFs on non-Windows OSs.

I won't have time to fix this right now but you are welcome to take a look yourself if its urgent. Adding a few `console.log`s reveals the problem is on line 61 of `dbfFile.js`. The `if` condition is never true, so the loop never terminates (but as I mentioned above it works fine on Windows). I suspect it comes down to some subtle difference in `fs` file handling between Windows and Linux/OSX.

**Comment by connorhu** [comment] 2016-03-09 10:50
In file dbf v7 the header fields length isn't 32 bytes.
http://www.dbase.com/KnowledgeBase/int/db7_file_fmt.htm

I have infinite loop because buffer.readUInt8(0) === 0x0D never be true because of field size.

**Comment by yortus** [comment] 2016-03-09 11:19
Hi @connorhu, is this the same issue as @dangreen's?

Only dBase III is supported, so I'm not surprised if it doesn't work with dBase 7 files. PRs are welcome.

**Comment by connorhu** [comment] 2016-03-09 16:24
I think yes. Is this lib supports 0x83 version on first bit?
(based on this: http://dbfviewer.com/dbf-file-structure/ )

**Comment by yortus** [comment] 2016-03-14 08:36
This issue _should_ now be resolved with the latest changes. If not, please feel free to re-open.

**Closed as completed by yortus** 2016-03-14 08:36 UTC
